package com.workmarket.search.model;

public enum SearchType {
	GLOBAL_CORE_SEARCH,
	PEOPLE_SEARCH,
	PEOPLE_SEARCH_ASSIGNMENT_FULL_NAME,
	PEOPLE_SEARCH_ASSESSMENT_INVITE,
	PEOPLE_SEARCH_ASSIGNMENT,
	PEOPLE_SEARCH_ELIGIBILITY,
	PEOPLE_SEARCH_GROUP,
	PEOPLE_SEARCH_GROUP_MEMBER,
	PEOPLE_SEARCH_TALENT_POOL_INVITE,
	PEOPLE_SEARCH_TYPE_AHEAD,
	WORK_ALL,
	WORK_KPI,
	WORK_FEED,
	WORK_FEED_ONBOARDING;
}
