package com.workmarket.domains.work.model.audit;

import java.util.List;

import com.google.common.collect.Lists;

public enum WorkAuditType {
	ENABLE_WORK_DIALER,
	RESEND,
	SEND,
	QUESTION,
	OFFER,
	OPEN_WORK,
	VOID,
	CANCEL,
	CREATE,
	DRAFT,
	ACCEPT,
	CLOSE,
	COMPLETE,
	DECLINE,
	ABANDON,
	INVOICE,
	PAY,
	REMOVE_FROM_INVOICE,
	DELETE_INVOICE,
	EDIT,
	REPRICE,
	RESOURCE_CONFIRM,
	RESOURCE_ACTIVE_CHECK_IN,
	RESOURCE_ACTIVE_CHECK_OUT,
	NOTE,
	ANSWER_QUESTION,
	ADD_ASSESSMENT,
	CHANGE_APPOINTMENT,
	REFUND,
	UNASSIGN,
	DELETE,
	INCOMPLETE,
	RESOLVE_SUBSTATUS,
	RESOLVE_SUBSTATUS_BY_ACTION,
	ADD_SUBSTATUS,
	ACTIVE,
	ABANDONED_EXCEPTION,
	PENDING_PAYMENT,
	RESOURCE_DECLINE,
	OFFER_APPROVE,
	OFFER_DECLINE,
	OFFER_CANCEL,
	OFFER_EXTEND,
	SEND_REMINDER_TO_COMPLETE,
	RESOURCE_APPLY,
	RESEND_UNDECLINE,
	CHANGE_CLIENT_PROJECT,
	WORK_NOTIFY,
	DOCUMENT_ATTACHMENT;

	public static final List<WorkAuditType> WORK_STATUS_CHANGE_AUDIT_TYPE = Lists.newArrayList();

	static {
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(SEND);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(OPEN_WORK);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(VOID);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(CANCEL);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(CREATE);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(DRAFT);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(ACCEPT);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(CLOSE);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(COMPLETE);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(DECLINE);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(ABANDON);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(REFUND);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(UNASSIGN);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(DELETE);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(ACTIVE);
		WORK_STATUS_CHANGE_AUDIT_TYPE.add(EDIT);
	}
}
