import { Map } from 'immutable';
import * as types from '../constants/actionTypes';

const initialSettingsState = Map({
	profileSubmitDisabled: false,
	fundsSubmitDisabled: false,
	creditCardFundsSubmitDisabled: false,
	taxSubmitDisabled: false,
	configSubmitDisabled: false,
	submitting: false,
	internalError: false,
	profileSubmitted: false,
	profileError: '',
	fundsSubmitted: false,
	fundsError: [],
	creditCardFundsSubmitted: false,
	creditCardFundsError: [],
	configSubmitted: false,
	googleInitialized: false,
	taxSubmitted: false,
	taxError: [],
	employees: [],
	employeeAddCount: 0,
	bulkEmployeeAddCount: 0
});

export { initialSettingsState };

const settings = (state = initialSettingsState, { type, error, value }) => {
	switch (type) {
	case types.GOOGLE_INITIALIZED:
		return state.set('googleInitialized', true);
	case types.PROFILE_FORM_SUBMIT_REQUEST:
		return state
			.set('submitDisabled', true)
			.set('submitting', true)
			.set('internalError', false)
			.set('profileSubmitted', false);
	case types.PROFILE_FORM_SUBMIT_ERROR:
		return state
			.set('submitDisabled', false)
			.set('submitting', false)
			.set('internalError', true)
			.set('profileError', error);
	case types.PROFILE_FORM_SUBMIT_SUCCESS:
		return state
			.set('profileSubmitted', true)
			.set('profileError', '');
	case types.FUNDS_FORM_SUBMIT_REQUEST:
		return state
			.set('fundsSubmitDisabled', true)
			.set('submitting', true)
			.set('internalError', false)
			.set('fundsError', []);
	case types.FUNDS_FORM_SUBMIT_SUCCESS:
		return state
			.set('fundsSubmitted', true)
			.set('fundsError', [])
			.set('submitting', false)
			.set('fundsSubmitDisabled', false);
	case types.FUNDS_FORM_SUBMIT_ERROR:
		return state
			.set('fundsSubmitDisabled', false)
			.set('submitting', false)
			.set('internalError', true)
			.set('fundsError', error);
	case types.ADD_FUNDS_VIA_CREDIT_CARD_FORM_SUBMIT_REQUEST:
		return state
			.set('creditCardFundsSubmitDisabled', true)
			.set('submitting', true)
			.set('internalError', false)
			.set('creditCardFundsError', []);
	case types.ADD_FUNDS_VIA_CREDIT_CARD_FORM_SUBMIT_SUCCESS:
		return state
			.set('creditCardFundsSubmitted', true)
			.set('creditCardFundsError', [])
			.set('submitting', false)
			.set('creditCardFundsSubmitDisabled', false);
	case types.ADD_FUNDS_VIA_CREDIT_CARD_FORM_SUBMIT_ERROR:
		return state
			.set('creditCardFundsSubmitDisabled', false)
			.set('submitting', false)
			.set('internalError', true)
			.set('creditCardFundsError', error);
	case types.ADD_EMPLOYEE_FORM_SUBMIT_REQUEST:
		return state
			.set('addEmployeeSubmitDisabled', true)
			.set('submitting', true)
			.set('internalError', false)
			.set('addEmployeeError', []);
	case types.ADD_EMPLOYEE_FORM_SUBMIT_SUCCESS:
		return state
			.set('addEmployeeError', [])
			.set('submitting', false)
			.set('addEmployeeSubmitDisabled', false)
			.set('employeeAddCount', state.get('employeeAddCount') + 1);
	case types.ADD_EMPLOYEE_FORM_SUBMIT_ERROR:
		return state
			.set('addEmployeeSubmitDisabled', false)
			.set('submitting', false)
			.set('internalError', true)
			.set('addEmployeeError', error);
	case types.ASSIGNMENT_PREFERENCES_FORM_SUBMIT_REQUEST:
		return state
			.set('assignmentPreferencesSubmitDisabled', true)
			.set('submitting', true)
			.set('internalError', false)
			.set('assignmentPreferencesError', []);
	case types.ASSIGNMENT_PREFERENCES_FORM_SUBMIT_SUCCESS:
		return state
			.set('assignmentPreferencesError', [])
			.set('submitting', false)
			.set('assignmentPreferencesSuccess', true)
			.set('assignmentPreferencesSubmitDisabled', false);
	case types.ASSIGNMENT_PREFERENCES_FORM_SUBMIT_ERROR:
		return state
			.set('assignmentPreferencesSubmitDisabled', false)
			.set('submitting', false)
			.set('internalError', true)
			.set('assignmentPreferencesError', error);
	case types.FIRST_ASSIGNMENT_FORM_SUBMIT_REQUEST:
		return state
			.set('firstAssignmentSubmitDisabled', true)
			.set('submitting', true)
			.set('internalError', false)
			.set('firstAssignmentError', []);
	case types.FIRST_ASSIGNMENT_FORM_SUBMIT_SUCCESS:
		return state
			.set('firstAssignmentSubmitDisabled', [])
			.set('submitting', false)
			.set('firstAssignmentSuccess', true)
			.set('firstAssignmentSubmitDisabled', false);
	case types.FIRST_ASSIGNMENT_FORM_SUBMIT_ERROR:
		return state
			.set('firstAssignmentSubmitDisabled', false)
			.set('submitting', false)
			.set('internalError', true)
			.set('firstAssignmentError', error);
	case types.FIRST_ASSIGNMENT_TEMPLATE_FORM_SUBMIT_REQUEST:
		return state
			.set('firstAssignmentTemplateSubmitDisabled', true)
			.set('submitting', true)
			.set('internalError', false)
			.set('firstAssignmentTemplateError', []);
	case types.FIRST_ASSIGNMENT_TEMPLATE_FORM_SUBMIT_SUCCESS:
		return state
			.set('firstAssignmentTemplateSubmitDisabled', [])
			.set('submitting', false)
			.set('firstAssignmentTemplateSuccess', true)
			.set('firstAssignmentTemplateSubmitDisabled', false);
	case types.FIRST_ASSIGNMENT_TEMPLATE_FORM_SUBMIT_ERROR:
		return state
			.set('firstAssignmentTemplateSubmitDisabled', false)
			.set('submitting', false)
			.set('internalError', true)
			.set('firstAssignmentTemplateError', error);
	case types.BULK_PROCESS_EMPLOYEES_SUCCESS:
		return state.set('bulkEmployeeAddCount', state.get('bulkEmployeeAddCount') + 1);
	case types.TAX_FORM_SUBMIT_REQUEST:
		return state
			.set('taxSubmitDisabled', true)
			.set('submitting', true)
			.set('internalError', false)
			.set('taxError', []);
	case types.TAX_FORM_SUBMIT_SUCCESS:
		return state
			.set('taxSubmitted', true)
			.set('taxError', [])
			.set('submitting', false)
			.set('taxSubmitDisabled', false);
	case types.TAX_FORM_SUBMIT_ERROR:
		return state
			.set('taxSubmitDisabled', false)
			.set('submitting', false)
			.set('internalError', true)
			.set('taxError', error);
	case types.GET_ASSIGNMENT_PREFERENCES_REQUEST:
		return state
			.set('submitting', true);
	case types.GET_ASSIGNMENT_PREFERENCES_SUCCESS:
		return state
			.set('submitting', false);
	case types.GET_ASSIGNMENT_PREFERENCES_ERROR:
		return state
			.set('submitting', false);
	case types.GET_FIRST_ASSIGNMENT_REQUEST:
		return state
			.set('submitting', true);
	case types.GET_FIRST_ASSIGNMENT_SUCCESS:
		return state
			.set('submitting', false);
	case types.GET_FIRST_ASSIGNMENT_ERROR:
		return state
			.set('submitting', false);
	case types.REFRESH_EMPLOYEE_LIST:
		return state
			.set('employees', value);
	default:
		return state;
	}
};

export default settings;
