export const ADD_CUSTOM_FIELDS = 'ADD_CUSTOM_FIELDS';
export const RECEIVE_CUSTOM_FIELDS = 'RECEIVE_CUSTOM_FIELDS';
export const UPDATE_CUSTOM_FIELD_DEFAULT = 'UPDATE_CUSTOM_FIELD_DEFAULT';
export const UPDATE_CUSTOM_FIELD_VALUE = 'UPDATE_CUSTOM_FIELD_VALUE';
export const REMOVE_CUSTOM_FIELD_GROUP = 'REMOVE_CUSTOM_FIELD_GROUP';
export const TOGGLE_CUSTOM_FIELD_REQUIRED = 'TOGGLE_CUSTOM_FIELD_REQUIRED';
export const RECEIVE_CUSTOM_FIELD_GROUP = 'RECEIVE_CUSTOM_FIELD_GROUP';
