package com.workmarket.domains.search.group.indexer.model;

import com.google.common.collect.Lists;
import com.workmarket.data.solr.model.SolrData;
import org.apache.solr.client.solrj.beans.Field;

import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class GroupSolrData implements SolrData, Serializable {

	private static final long serialVersionUID = 5948521890737572792L;

	private long id;
	private String uuid;
	private Float score;
	private String name;
	private String nameSort;
	private String description;
	private Boolean openMembership;
	private Boolean requiresApproval;

	private List<Long> requiredLicenseIds = Lists.newArrayList();
	private List<String> requiredLicenseNames = Lists.newArrayList();
	private List<String> requiredLicenseDescriptions = Lists.newArrayList();

	private List<Long> requiredCertificationIds = Lists.newArrayList();
	private List<String> requiredCertificationNames = Lists.newArrayList();
	private List<String> requiredCertificationDescriptions = Lists.newArrayList();

	private List<Long> requiredAssessmentIds = Lists.newArrayList();
	private List<String> requiredAssessmentNames = Lists.newArrayList();
	private List<String> requiredAssessmentDescriptions = Lists.newArrayList();

	private List<Long> requiredIndustryIds = Lists.newArrayList();
	private List<String> requiredIndustryNames = Lists.newArrayList();
	private List<String> requiredIndustryDescriptions = Lists.newArrayList();

	private List<Long> requiredInsuranceIds = Lists.newArrayList();
	private List<String> requiredInsuranceNames = Lists.newArrayList();
	private List<String> requiredInsuranceDescriptions = Lists.newArrayList();

	private List<Long> requiredLocationIds = Lists.newArrayList();
	private List<String> requiredLocationNames = Lists.newArrayList();
	private List<String> requiredLocationDescriptions = Lists.newArrayList();

	private List<Long> requiredAddressesIds = Lists.newArrayList();
	private List<String> requiredAddressesNames = Lists.newArrayList();
	private List<String> requiredAddressesDescriptions = Lists.newArrayList();

	private Integer locationRadius;
	private Integer addressRadius;

	private List<Long> requiredContractIds = Lists.newArrayList();
	private List<String> requiredContractNames = Lists.newArrayList();
	private List<String> requiredContractDescriptions = Lists.newArrayList();

	private List<Long> requiredVerificationIds = Lists.newArrayList();

	private List<Long> networkIds = Lists.newArrayList();

	private Boolean autoGenerated;
	private Long companyId;
	private String companyName;
	private String effectiveCompanyName;
	private String allFields;

	private Integer memberCount = 0;
	private Double averageUserRating;
	private Date createdOn;

	private String requirementsPostalCode;
	private Double requirementsMaxTravelDistance;

	private List<Long> industryIds = Lists.newArrayList();
	private List<String> industryNames = Lists.newArrayList();
	private List<String> industryDescriptions = Lists.newArrayList();

	private List<Long> skillIds = Lists.newArrayList();
	private List<String> skillNames = Lists.newArrayList();

	private Double lat;
	private Double lng;
	private Double distance;

	private Integer requirementsRatingValue;

	private Double requirementsHourlyRateMinimum;
	private Double requirementsHourlyRateMaximum;

	private Boolean backgroundCheckedFlag;
	private Boolean drugTestedFlag;

	private String companyType;

	private Boolean lane0Flag = Boolean.FALSE;
	private Boolean lane1Flag = Boolean.FALSE;
	private Boolean lane2Flag = Boolean.FALSE;
	private Boolean lane3Flag = Boolean.FALSE;
	private Boolean lane4Flag = Boolean.FALSE;

	private Boolean termsRequired;

	private Boolean hasLaneRequirements;
	private Boolean hasRatingRequirements;
	private Boolean hasRateRequirements;
	private Boolean hasLocationRequirements;
	private Boolean hasLicenseRequirements;
	private Boolean hasInsuranceRequirements;
	private Boolean hasCertificationRequirements;
	private Boolean hasAssessmentRequirements;
	private Boolean hasRequirements;

	private Long creatorId;

	private Boolean hasIndustriesRequirements;
	private Boolean hasAvailabilityRequirements;

	private Integer mondayFromTime;
	private Integer mondayToTime;
	private Boolean mondayAllDay;

	private Integer tuesdayFromTime;
	private Integer tuesdayToTime;
	private Boolean tuesdayAllDay;

	private Integer wednesdayFromTime;
	private Integer wednesdayToTime;
	private Boolean wednesdayAllDay;

	private Integer thursdayFromTime;
	private Integer thursdayToTime;
	private Boolean thursdayAllDay;

	private Integer fridayFromTime;
	private Integer fridayToTime;
	private Boolean fridayAllDay;

	private Integer saturdayFromTime;
	private Integer saturdayToTime;
	private Boolean saturdayAllDay;

	private Integer sundayFromTime;
	private Integer sundayToTime;
	private Boolean sundayAllDay;

	private Boolean activeFlag;
	private Boolean deleted;
	private Boolean searchable;

	private Boolean authorizedToJoin = Boolean.FALSE;

	private Integer messageCount = 0;

	private String avatarOriginalUri;
	private String avatarLargeUri;
	private String avatarSmallUri;

	private String creatorFullName;
	private String creatorUserNumber;

	private String objectiveType;
	private String objective;

	private Double totalThroughput;
	private Date lastRoutedOn;

	public GroupSolrData() {
	}

	@Override
	public long getId() {
		return id;
	}

	@Field
	public GroupSolrData setId(long id) {
		this.id = id;
		return this;
	}

	public String getUuid() {
		return uuid;
	}

	@Field
	public GroupSolrData setUuid(final String uuid) {
		this.uuid = uuid;
		return this;
	}

	public String getAllFields() {
		return allFields;
	}

	@Field
	public GroupSolrData setAllFields(String allFields) {
		this.allFields = allFields;
		return this;
	}

	public String getName() {
		return name;
	}

	@Field
	public GroupSolrData setName(String name) {
		this.name = name;
		return this;
	}

	public String getDescription() {
		return description;
	}

	@Field
	public GroupSolrData setDescription(String description) {
		this.description = description;
		return this;
	}

	@Field
	public GroupSolrData setOpenMembership(Boolean openMembership) {
		this.openMembership = openMembership;
		return this;
	}

	public Boolean getRequiresApproval() {
		return requiresApproval;
	}

	@Field
	public GroupSolrData setRequiresApproval(Boolean requiresApproval) {
		this.requiresApproval = requiresApproval;
		return this;
	}

	public List<Long> getRequiredLicenseIds() {
		return requiredLicenseIds;
	}

	@Field
	public GroupSolrData setRequiredLicenseIds(List<Long> requiredLicenseIds) {
		this.requiredLicenseIds = requiredLicenseIds;
		return this;
	}

	public List<Long> getRequiredCertificationIds() {
		return requiredCertificationIds;
	}

	@Field
	public GroupSolrData setRequiredCertificationIds(List<Long> requiredCertificationIds) {
		this.requiredCertificationIds = requiredCertificationIds;
		return this;
	}

	public List<Long> getRequiredAssessmentIds() {
		return requiredAssessmentIds;
	}

	@Field
	public GroupSolrData setRequiredAssessmentIds(List<Long> requiredAssessmentIds) {
		this.requiredAssessmentIds = requiredAssessmentIds;
		return this;
	}

	public Boolean getAutoGenerated() {
		return autoGenerated;
	}

	@Field
	public GroupSolrData setAutoGenerated(Boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
		return this;
	}

	public Long getCompanyId() {
		return companyId;
	}

	@Field
	public GroupSolrData setCompanyId(Long companyId) {
		this.companyId = companyId;
		return this;
	}

	public String getCompanyName() {
		return companyName;
	}

	@Field
	public GroupSolrData setCompanyName(String companyName) {
		this.companyName = companyName;
		return this;
	}

	public String getEffectiveCompanyName() {
		return effectiveCompanyName;
	}

	@Field
	public GroupSolrData setEffectiveCompanyName(String effectiveCompanyName) {
		this.effectiveCompanyName = effectiveCompanyName;
		return this;
	}

	public List<String> getRequiredLicenseNames() {
		return requiredLicenseNames;
	}

	@Field
	public GroupSolrData setRequiredLicenseNames(List<String> requiredLicenseNames) {
		this.requiredLicenseNames = requiredLicenseNames;
		return this;
	}

	public List<String> getRequiredCertificationNames() {
		return requiredCertificationNames;
	}

	@Field
	public GroupSolrData setRequiredCertificationNames(List<String> requiredCertificationNames) {
		this.requiredCertificationNames = requiredCertificationNames;
		return this;
	}

	public List<String> getRequiredAssessmentNames() {
		return requiredAssessmentNames;
	}

	@Field
	public GroupSolrData setRequiredAssessmentNames(List<String> requiredAssessmentNames) {
		this.requiredAssessmentNames = requiredAssessmentNames;
		return this;
	}

	public List<String> getRequiredLicenseDescriptions() {
		return requiredLicenseDescriptions;
	}

	@Field
	public GroupSolrData setRequiredLicenseDescriptions(List<String> requiredLicenseDescriptions) {
		this.requiredLicenseDescriptions = requiredLicenseDescriptions;
		return this;
	}

	public List<String> getRequiredCertificationDescriptions() {
		return requiredCertificationDescriptions;
	}

	@Field
	public GroupSolrData setRequiredCertificationDescriptions(List<String> requiredCertificationDescriptions) {
		this.requiredCertificationDescriptions = requiredCertificationDescriptions;
		return this;
	}

	public List<String> getRequiredAssessmentDescriptions() {
		return requiredAssessmentDescriptions;
	}

	@Field
	public GroupSolrData setRequiredAssessmentDescriptions(List<String> requiredAssessmentDescriptions) {
		this.requiredAssessmentDescriptions = requiredAssessmentDescriptions;
		return this;
	}

	public Boolean getOpenMembership() {
		return openMembership;
	}

	public Integer getMemberCount() {
		return memberCount;
	}

	@Field
	public GroupSolrData setMemberCount(Integer memberCount) {
		this.memberCount = memberCount;
		return this;
	}

	public Double getAverageUserRating() {
		return averageUserRating;
	}

	@Field
	public GroupSolrData setAverageUserRating(Double averageUserRating) {
		this.averageUserRating = averageUserRating;
		return this;
	}

	public Date getCreatedOn() {
		return createdOn;
	}

	@Field
	public GroupSolrData setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
		return this;
	}

	@Field
	public GroupSolrData setLastRoutedOn(Date lastRoutedOn) {
		this.lastRoutedOn = lastRoutedOn;
		return this;
	}

	public Date getLastRoutedOn() {
		return this.lastRoutedOn;
	}

	public String getRequirementsPostalCode() {
		return requirementsPostalCode;
	}

	@Field
	public GroupSolrData setRequirementsPostalCode(String requirementsPostalCode) {
		this.requirementsPostalCode = requirementsPostalCode;
		return this;
	}

	public Double getRequirementsMaxTravelDistance() {
		return requirementsMaxTravelDistance;
	}

	@Field
	public GroupSolrData setRequirementsMaxTravelDistance(Double requirementsMaxTravelDistance) {
		this.requirementsMaxTravelDistance = requirementsMaxTravelDistance;
		return this;
	}

	public List<Long> getIndustryIds() {
		return industryIds;
	}

	@Field
	public GroupSolrData setIndustryIds(List<Long> industryIds) {
		this.industryIds = industryIds;
		return this;
	}

	public List<Long> getSkillIds() {
		return skillIds;
	}

	@Field
	public GroupSolrData setSkillIds(final List<Long> skillIds) {
		this.skillIds = skillIds;
		return this;
	}

	public List<String> getSkillNames() {
		return skillNames;
	}

	@Field
	public GroupSolrData setSkillNames(final List<String> skillNames) {
		this.skillNames = skillNames;
		return this;
	}

	public Double getLat() {
		return lat;
	}

	@Field
	public GroupSolrData setLat(Double lat) {
		this.lat = lat;
		return this;
	}

	public Double getLng() {
		return lng;
	}

	@Field
	public GroupSolrData setLng(Double lng) {
		this.lng = lng;
		return this;
	}

	public Double getDistance() {
		return distance;
	}

	@Field
	public GroupSolrData setDistance(Double distance) {
		this.distance = distance;
		return this;
	}

	public Boolean getBackgroundCheckedFlag() {
		return backgroundCheckedFlag;
	}

	@Field
	public GroupSolrData setBackgroundCheckedFlag(Boolean backgroundCheckedFlag) {
		this.backgroundCheckedFlag = backgroundCheckedFlag;
		return this;
	}

	public Boolean getDrugTestedFlag() {
		return drugTestedFlag;
	}

	@Field
	public GroupSolrData setDrugTestedFlag(Boolean drugTestedFlag) {
		this.drugTestedFlag = drugTestedFlag;
		return this;
	}

	public Boolean getLane0Flag() {
		return lane0Flag;
	}

	@Field
	public GroupSolrData setLane0Flag(Boolean lane0Flag) {
		this.lane0Flag = lane0Flag;
		return this;
	}

	public Boolean getLane1Flag() {
		return lane1Flag;
	}

	@Field
	public GroupSolrData setLane1Flag(Boolean lane1Flag) {
		this.lane1Flag = lane1Flag;
		return this;
	}

	public Boolean getLane2Flag() {
		return lane2Flag;
	}

	@Field
	public GroupSolrData setLane2Flag(Boolean lane2Flag) {
		this.lane2Flag = lane2Flag;
		return this;
	}

	public Boolean getLane3Flag() {
		return lane3Flag;
	}

	@Field
	public GroupSolrData setLane3Flag(Boolean lane3Flag) {
		this.lane3Flag = lane3Flag;
		return this;
	}

	public Boolean getLane4Flag() {
		return lane4Flag;
	}

	@Field
	public GroupSolrData setLane4Flag(Boolean lane4Flag) {
		this.lane4Flag = lane4Flag;
		return this;
	}

	public Boolean getTermsRequired() {
		return termsRequired;
	}

	@Field
	public GroupSolrData setTermsRequired(Boolean termsRequired) {
		this.termsRequired = termsRequired;
		return this;
	}

	public Boolean getHasLaneRequirements() {
		return hasLaneRequirements;
	}

	@Field
	public GroupSolrData setHasLaneRequirements(Boolean hasLaneRequirements) {
		this.hasLaneRequirements = hasLaneRequirements;
		return this;
	}

	public Boolean getHasRatingRequirements() {
		return hasRatingRequirements;
	}

	@Field
	public GroupSolrData setHasRatingRequirements(Boolean hasRatingRequirements) {
		this.hasRatingRequirements = hasRatingRequirements;
		return this;
	}

	public Boolean getHasRateRequirements() {
		return hasRateRequirements;
	}

	@Field
	public GroupSolrData setHasRateRequirements(Boolean hasRateRequirements) {
		this.hasRateRequirements = hasRateRequirements;
		return this;
	}

	public Boolean getHasLocationRequirements() {
		return hasLocationRequirements;
	}

	@Field
	public GroupSolrData setHasLocationRequirements(Boolean hasLocationRequirements) {
		this.hasLocationRequirements = hasLocationRequirements;
		return this;
	}

	public Boolean getHasLicenseRequirements() {
		return hasLicenseRequirements;
	}

	@Field
	public GroupSolrData setHasLicenseRequirements(Boolean hasLicenseRequirements) {
		this.hasLicenseRequirements = hasLicenseRequirements;
		return this;
	}

	public Boolean getHasInsuranceRequirements() {
		return hasInsuranceRequirements;
	}

	@Field
	public GroupSolrData setHasInsuranceRequirements(Boolean hasInsuranceRequirements) {
		this.hasInsuranceRequirements = hasInsuranceRequirements;
		return this;
	}

	public Boolean getHasCertificationRequirements() {
		return hasCertificationRequirements;
	}

	@Field
	public GroupSolrData setHasCertificationRequirements(Boolean hasCertificationRequirements) {
		this.hasCertificationRequirements = hasCertificationRequirements;
		return this;
	}

	public Boolean getHasAssessmentRequirements() {
		return hasAssessmentRequirements;
	}

	@Field
	public GroupSolrData setHasAssessmentRequirements(Boolean hasAssessmentRequirements) {
		this.hasAssessmentRequirements = hasAssessmentRequirements;
		return this;
	}

	public Boolean getHasRequirements() {
		return hasRequirements;
	}

	@Field
	public GroupSolrData setHasRequirements(Boolean hasRequirements) {
		this.hasRequirements = hasRequirements;
		return this;
	}

	public List<Long> getRequiredVerificationIds() {
		return requiredVerificationIds;
	}

	@Field
	public GroupSolrData setRequiredVerificationIds(List<Long> requiredVerificationIds) {
		this.requiredVerificationIds = requiredVerificationIds;
		return this;
	}

	public List<String> getIndustryNames() {
		return industryNames;
	}

	@Field
	public GroupSolrData setIndustryNames(List<String> industryNames) {
		this.industryNames = industryNames;
		return this;
	}

	public List<String> getIndustryDescriptions() {
		return industryDescriptions;
	}

	@Field
	public GroupSolrData setIndustryDescriptions(List<String> industryDescriptions) {
		this.industryDescriptions = industryDescriptions;
		return this;
	}

	public List<Long> getRequiredIndustryIds() {
		return requiredIndustryIds;
	}

	@Field
	public GroupSolrData setRequiredIndustryIds(List<Long> requiredIndustryIds) {
		this.requiredIndustryIds = requiredIndustryIds;
		return this;
	}

	public List<String> getRequiredIndustryNames() {
		return requiredIndustryNames;
	}

	@Field
	public GroupSolrData setRequiredIndustryNames(List<String> requiredIndustryNames) {
		this.requiredIndustryNames = requiredIndustryNames;
		return this;
	}

	public List<String> getRequiredIndustryDescriptions() {
		return requiredIndustryDescriptions;
	}

	@Field
	public GroupSolrData setRequiredIndustryDescriptions(List<String> requiredIndustryDescriptions) {
		this.requiredIndustryDescriptions = requiredIndustryDescriptions;
		return this;
	}

	public List<Long> getRequiredInsuranceIds() {
		return requiredInsuranceIds;
	}

	@Field
	public GroupSolrData setRequiredInsuranceIds(List<Long> requiredInsuranceIds) {
		this.requiredInsuranceIds = requiredInsuranceIds;
		return this;
	}

	public List<String> getRequiredInsuranceNames() {
		return requiredInsuranceNames;
	}

	@Field
	public GroupSolrData setRequiredInsuranceNames(List<String> requiredInsuranceNames) {
		this.requiredInsuranceNames = requiredInsuranceNames;
		return this;
	}

	public List<String> getRequiredInsuranceDescriptions() {
		return requiredInsuranceDescriptions;
	}

	@Field
	public GroupSolrData setRequiredInsuranceDescriptions(
			List<String> requiredInsuranceDescriptions) {
		this.requiredInsuranceDescriptions = requiredInsuranceDescriptions;
		return this;
	}

	public Integer getRequirementsRatingValue() {
		return requirementsRatingValue;
	}

	@Field
	public GroupSolrData setRequirementsRatingValue(Integer requirementsRatingValue) {
		this.requirementsRatingValue = requirementsRatingValue;
		return this;
	}

	public Double getRequirementsHourlyRateMinimum() {
		return requirementsHourlyRateMinimum;
	}

	@Field
	public GroupSolrData setRequirementsHourlyRateMinimum(Double requirementsHourlyRateMinimum) {
		this.requirementsHourlyRateMinimum = requirementsHourlyRateMinimum;
		return this;
	}

	public Double getRequirementsHourlyRateMaximum() {
		return requirementsHourlyRateMaximum;
	}

	@Field
	public GroupSolrData setRequirementsHourlyRateMaximum(Double requirementsHourlyRateMaximum) {
		this.requirementsHourlyRateMaximum = requirementsHourlyRateMaximum;
		return this;
	}

	public Long getCreatorId() {
		return creatorId;
	}

	@Field
	public GroupSolrData setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
		return this;
	}

	public Boolean getHasIndustriesRequirements() {
		return hasIndustriesRequirements;
	}

	@Field
	public GroupSolrData setHasIndustriesRequirements(Boolean hasIndustriesRequirements) {
		this.hasIndustriesRequirements = hasIndustriesRequirements;
		return this;
	}

	public Boolean getHasAvailabilityRequirements() {
		return hasAvailabilityRequirements;
	}

	@Field
	public GroupSolrData setHasAvailabilityRequirements(Boolean hasAvailabilityRequirements) {
		this.hasAvailabilityRequirements = hasAvailabilityRequirements;
		return this;
	}

	public Integer getMondayFromTime() {
		return mondayFromTime;
	}

	@Field
	public GroupSolrData setMondayFromTime(Integer mondayFromTime) {
		this.mondayFromTime = mondayFromTime;
		return this;
	}

	public Integer getMondayToTime() {
		return mondayToTime;
	}

	@Field
	public GroupSolrData setMondayToTime(Integer mondayToTime) {
		this.mondayToTime = mondayToTime;
		return this;
	}

	public Boolean getMondayAllDay() {
		return mondayAllDay;
	}

	@Field
	public GroupSolrData setMondayAllDay(Boolean mondayAllDay) {
		this.mondayAllDay = mondayAllDay;
		return this;
	}

	public Integer getTuesdayFromTime() {
		return tuesdayFromTime;
	}

	@Field
	public GroupSolrData setTuesdayFromTime(Integer tuesdayFromTime) {
		this.tuesdayFromTime = tuesdayFromTime;
		return this;
	}

	public Integer getTuesdayToTime() {
		return tuesdayToTime;
	}

	@Field
	public GroupSolrData setTuesdayToTime(Integer tuesdayToTime) {
		this.tuesdayToTime = tuesdayToTime;
		return this;
	}

	public Boolean getTuesdayAllDay() {
		return tuesdayAllDay;
	}

	@Field
	public GroupSolrData setTuesdayAllDay(Boolean tuesdayAllDay) {
		this.tuesdayAllDay = tuesdayAllDay;
		return this;
	}

	public Integer getWednesdayFromTime() {
		return wednesdayFromTime;
	}

	@Field
	public GroupSolrData setWednesdayFromTime(Integer wednesdayFromTime) {
		this.wednesdayFromTime = wednesdayFromTime;
		return this;
	}

	public Integer getWednesdayToTime() {
		return wednesdayToTime;
	}

	@Field
	public GroupSolrData setWednesdayToTime(Integer wednesdayToTime) {
		this.wednesdayToTime = wednesdayToTime;
		return this;
	}

	public Boolean getWednesdayAllDay() {
		return wednesdayAllDay;
	}

	@Field
	public GroupSolrData setWednesdayAllDay(Boolean wednesdayAllDay) {
		this.wednesdayAllDay = wednesdayAllDay;
		return this;
	}

	public Integer getThursdayFromTime() {
		return thursdayFromTime;
	}

	@Field
	public GroupSolrData setThursdayFromTime(Integer thursdayFromTime) {
		this.thursdayFromTime = thursdayFromTime;
		return this;
	}

	public Integer getThursdayToTime() {
		return thursdayToTime;
	}

	@Field
	public GroupSolrData setThursdayToTime(Integer thursdayToTime) {
		this.thursdayToTime = thursdayToTime;
		return this;
	}

	public Boolean getThursdayAllDay() {
		return thursdayAllDay;
	}

	@Field
	public GroupSolrData setThursdayAllDay(Boolean thursdayAllDay) {
		this.thursdayAllDay = thursdayAllDay;
		return this;
	}

	public Integer getFridayFromTime() {
		return fridayFromTime;
	}

	@Field
	public GroupSolrData setFridayFromTime(Integer fridayFromTime) {
		this.fridayFromTime = fridayFromTime;
		return this;
	}

	public Integer getFridayToTime() {
		return fridayToTime;
	}

	@Field
	public GroupSolrData setFridayToTime(Integer fridayToTime) {
		this.fridayToTime = fridayToTime;
		return this;
	}

	public Boolean getFridayAllDay() {
		return fridayAllDay;
	}

	@Field
	public GroupSolrData setFridayAllDay(Boolean fridayAllDay) {
		this.fridayAllDay = fridayAllDay;
		return this;
	}

	public Integer getSaturdayFromTime() {
		return saturdayFromTime;
	}

	@Field
	public GroupSolrData setTotalThroughput(Double totalThroughput) {
		this.totalThroughput = totalThroughput;
		return this;
	}

	public Double getTotalThroughput() {
		return this.totalThroughput;
	}

	@Field
	public GroupSolrData setSaturdayFromTime(Integer saturdayFromTime) {
		this.saturdayFromTime = saturdayFromTime;
		return this;
	}

	public Integer getSaturdayToTime() {
		return saturdayToTime;
	}

	@Field
	public GroupSolrData setSaturdayToTime(Integer saturdayToTime) {
		this.saturdayToTime = saturdayToTime;
		return this;
	}

	public Boolean getSaturdayAllDay() {
		return saturdayAllDay;
	}

	@Field
	public GroupSolrData setSaturdayAllDay(Boolean saturdayAllDay) {
		this.saturdayAllDay = saturdayAllDay;
		return this;
	}

	public Integer getSundayFromTime() {
		return sundayFromTime;
	}

	@Field
	public GroupSolrData setSundayFromTime(Integer sundayFromTime) {
		this.sundayFromTime = sundayFromTime;
		return this;
	}

	public Integer getSundayToTime() {
		return sundayToTime;
	}

	@Field
	public GroupSolrData setSundayToTime(Integer sundayToTime) {
		this.sundayToTime = sundayToTime;
		return this;
	}

	public Boolean getSundayAllDay() {
		return sundayAllDay;
	}

	@Field
	public GroupSolrData setSundayAllDay(Boolean sundayAllDay) {
		this.sundayAllDay = sundayAllDay;
		return this;
	}

	public String getNameSort() {
		return nameSort;
	}

	@Field
	public GroupSolrData setNameSort(String nameSort) {
		this.nameSort = nameSort;
		return this;
	}

	public Boolean getActiveFlag() {
		return activeFlag;
	}

	@Field
	public GroupSolrData setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
		return this;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	@Field
	public GroupSolrData setDeleted(Boolean deleted) {
		this.deleted = deleted;
		return this;
	}

	public Integer getMessageCount() {
		return messageCount;
	}

	@Field
	public GroupSolrData setMessageCount(Integer messageCount) {
		this.messageCount = messageCount;
		return this;
	}

	public List<Long> getRequiredLocationIds() {
		return requiredLocationIds;
	}

	@Field
	public GroupSolrData setRequiredLocationIds(List<Long> requiredLocationIds) {
		this.requiredLocationIds = requiredLocationIds;
		return this;
	}

	public List<String> getRequiredLocationNames() {
		return requiredLocationNames;
	}

	@Field
	public GroupSolrData setRequiredLocationNames(List<String> requiredLocationNames) {
		this.requiredLocationNames = requiredLocationNames;
		return this;
	}

	public List<String> getRequiredLocationDescriptions() {
		return requiredLocationDescriptions;
	}

	@Field
	public GroupSolrData setRequiredLocationDescriptions(List<String> requiredLocationDescriptions) {
		this.requiredLocationDescriptions = requiredLocationDescriptions;
		return this;
	}

	public Integer getLocationRadius() {
		return locationRadius;
	}

	@Field
	public GroupSolrData setLocationRadius(Integer locationRadius) {
		this.locationRadius = locationRadius;
		return this;
	}

	public Integer getAddressRadius() {
		return addressRadius;
	}

	@Field
	public GroupSolrData setAddressRadius(Integer addressRadius) {
		this.addressRadius = addressRadius;
		return this;
	}

	public List<Long> getRequiredAddressesIds() {
		return requiredAddressesIds;
	}

	@Field
	public GroupSolrData setRequiredAddressesIds(List<Long> requiredAddressesIds) {
		this.requiredAddressesIds = requiredAddressesIds;
		return this;
	}

	public List<String> getRequiredAddressesNames() {
		return requiredAddressesNames;
	}

	@Field
	public GroupSolrData setRequiredAddressesNames(List<String> requiredAddressesNames) {
		this.requiredAddressesNames = requiredAddressesNames;
		return this;
	}

	public List<String> getRequiredAddressesDescriptions() {
		return requiredAddressesDescriptions;
	}

	@Field
	public GroupSolrData setRequiredAddressesDescriptions(List<String> requiredAddressesDescriptions) {
		this.requiredAddressesDescriptions = requiredAddressesDescriptions;
		return this;
	}

	public List<Long> getRequiredContractIds() {
		return requiredContractIds;
	}

	@Field
	public GroupSolrData setRequiredContractIds(List<Long> requiredContractIds) {
		this.requiredContractIds = requiredContractIds;
		return this;
	}

	public List<String> getRequiredContractNames() {
		return requiredContractNames;
	}

	@Field
	public GroupSolrData setRequiredContractNames(List<String> requiredContractNames) {
		this.requiredContractNames = requiredContractNames;
		return this;
	}

	public List<String> getRequiredContractDescriptions() {
		return requiredContractDescriptions;
	}

	@Field
	public GroupSolrData setRequiredContractDescriptions(List<String> requiredContractDescriptions) {
		this.requiredContractDescriptions = requiredContractDescriptions;
		return this;
	}

	public String getCompanyType() {
		return companyType;
	}

	@Field
	public GroupSolrData setCompanyType(String companyType) {
		this.companyType = companyType;
		return this;
	}

	public String getAvatarAssetOriginalUri() {
		return avatarOriginalUri;
	}

	@Field
	public GroupSolrData setAvatarAssetOriginalUri(String avatarOriginalUri) {
		this.avatarOriginalUri = avatarOriginalUri;
		return this;
	}

	public String getAvatarAssetLargeUri() {
		return avatarLargeUri;
	}

	@Field
	public GroupSolrData setAvatarAssetLargeUri(String avatarLargeUri) {
		this.avatarLargeUri = avatarLargeUri;
		return this;
	}

	public String getAvatarAssetSmallUri() {
		return avatarSmallUri;
	}

	@Field
	public GroupSolrData setAvatarAssetSmallUri(String avatarSmallUri) {
		this.avatarSmallUri = avatarSmallUri;
		return this;
	}

	public String getCreatorFullName() {
		return creatorFullName;
	}

	@Field
	public GroupSolrData setCreatorFullName(String creatorFullName) {
		this.creatorFullName = creatorFullName;
		return this;
	}

	public String getCreatorUserNumber() {
		return creatorUserNumber;
	}

	@Field
	public GroupSolrData setCreatorUserNumber(String creatorUserNumber) {
		this.creatorUserNumber = creatorUserNumber;
		return this;
	}

	public String getObjectiveType() {
		return objectiveType;
	}

	@Field
	public GroupSolrData setObjectiveType(String objectiveType) {
		this.objectiveType = objectiveType;
		return this;
	}

	public String getObjective() {
		return objective;
	}

	@Field
	public GroupSolrData setObjective(String objective) {
		this.objective = objective;
		return this;
	}

	public Boolean getAuthorizedToJoin() {
		return this.authorizedToJoin;
	}

	@Transient
	public GroupSolrData setAuthorizedToJoin(Boolean authorizedToJoin) {
		this.authorizedToJoin = authorizedToJoin;
		return this;
	}

	@Transient
	public Boolean getHasMondayAvailability() {
		return checkAvailabilityRequirement(getMondayFromTime(), getMondayToTime(), getMondayAllDay());
	}

	@Transient
	public Boolean getHasTuesdayAvailability() {
		return checkAvailabilityRequirement(getTuesdayFromTime(), getTuesdayToTime(), getTuesdayAllDay());
	}

	@Transient
	public Boolean getHasWednesdayAvailability() {
		return checkAvailabilityRequirement(getWednesdayFromTime(), getWednesdayToTime(), getWednesdayAllDay());
	}

	@Transient
	public Boolean getHasThursdayAvailability() {
		return checkAvailabilityRequirement(getThursdayFromTime(), getThursdayToTime(), getThursdayAllDay());
	}

	@Transient
	public Boolean getHasFridayAvailability() {
		return checkAvailabilityRequirement(getFridayFromTime(), getFridayToTime(), getFridayAllDay());
	}

	@Transient
	public Boolean getHasSaturdayAvailability() {
		return checkAvailabilityRequirement(getSaturdayFromTime(), getSaturdayToTime(), getSaturdayAllDay());
	}

	@Transient
	public Boolean getHasSundayAvailability() {
		return checkAvailabilityRequirement(getSundayFromTime(), getSundayToTime(), getSundayAllDay());
	}

	private Boolean checkAvailabilityRequirement(Integer from, Integer to, Boolean allDay) {
		return !(allDay == null && from == null && to == null);
	}

	@Field
	public GroupSolrData setSearchable(Boolean searchable) {
		this.searchable = searchable;
		return this;
	}

	public Boolean getSearchable() {
		return searchable;
	}

	@Field
	public GroupSolrData setNetworkIds(List<Long> networkIds) {
		this.networkIds = networkIds;
		return this;
	}

	public List<Long> getNetworkIds() {
		return networkIds;
	}

	public Float getScore() {
		return score;
	}

	@Field
	public GroupSolrData setScore(Float score) {
		this.score = score;
		return this;
	}
}
