package com.workmarket.domains.groups.model;

import com.google.common.collect.ImmutableList;
import com.workmarket.api.v2.model.OrgUnitDTO;

import java.util.Calendar;
import java.util.List;

public class ManagedCompanyUserGroupRow {

	private Long groupId;
	private String name;
	private String description;
	private Boolean openMembership;
	private Boolean searchable;
	private Boolean requiresApproval;
	private Boolean autoGenerated;
	private Boolean activeFlag;
	private Boolean deleted;
	private Boolean published;
	private Long industry;

	private Long companyId;
	private String companyName;
	private String effectiveCompanyName;
	private String companyLargeAvatarUri;
	private String companySmallAvatarUri;

	private Calendar dateApplied;
	private Calendar dateApproved;
	private Calendar dateInvited;
	private boolean member;
	private boolean owner;
	private boolean isShared;

	private Integer memberCount = 0;
	private Integer pendingApplicantCount = 0;
	private Integer invitedApplicantCount = 0;

	private Calendar createdOn;
	private Long creatorId;
	private String creatorFullName;
	private String ownerUserNumber;
	private String ownerId;
	private String ownerFullName;
	private String uuid;
	private List<OrgUnitDTO> orgUnits = ImmutableList.of();

	public List<OrgUnitDTO> getOrgUnits() {
		return orgUnits;
	}

	public void setOrgUnits(final List<OrgUnitDTO> orgUnits) {
		this.orgUnits = ImmutableList.copyOf(orgUnits);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean isOpenMembership() { return openMembership; }

	public void setOpenMembership(Boolean openMembership) {
		this.openMembership = openMembership;
	}

	public Boolean getSearchable() {
		return this.searchable;
	}

	public void setSearchable(Boolean searchable) {
		this.searchable = searchable;
	}

	public Boolean getRequiresApproval() {
		return requiresApproval;
	}

	public void setRequiresApproval(Boolean requiresApproval) {
		this.requiresApproval = requiresApproval;
	}

	public Boolean getAutoGenerated() {
		return autoGenerated;
	}

	public void setAutoGenerated(Boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}

	public Boolean getActiveFlag() {
		return activeFlag;
	}

	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Boolean getPublished() {
		return published;
	}

	public void setPublished(Boolean published) {
		this.published = published;
	}

	public Long getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getEffectiveCompanyName() {
		return effectiveCompanyName;
	}

	public void setEffectiveCompanyName(String effectiveCompanyName) {
		this.effectiveCompanyName = effectiveCompanyName;
	}

	public String getCompanyLargeAvatarUri() {
		return companyLargeAvatarUri;
	}

	public void setCompanyLargeAvatarUri(String companyLargeAvatarUri) { this.companyLargeAvatarUri = companyLargeAvatarUri; }

	public String getCompanySmallAvatarUri() {
		return companySmallAvatarUri;
	}

	public void setCompanySmallAvatarUri(String companySmallAvatarUri) { this.companySmallAvatarUri = companySmallAvatarUri; }

	public Calendar getDateApplied() {
		return dateApplied;
	}

	public void setDateApplied(Calendar dateApplied) {
		this.dateApplied = dateApplied;
	}

	public Calendar getDateApproved() {
		return dateApproved;
	}

	public void setDateApproved(Calendar dateApproved) {
		this.dateApproved = dateApproved;
	}

	public Calendar getDateInvited() {
		return dateInvited;
	}

	public void setDateInvited(Calendar dateInvited) {
		this.dateInvited = dateInvited;
	}

	public Integer getMemberCount() {
		return memberCount;
	}

	public void setMemberCount(Integer memberCount) {
		this.memberCount = memberCount;
	}

	public Integer getPendingApplicantCount() {
		return pendingApplicantCount;
	}

	public void setPendingApplicantCount(Integer pendingApplicantCount) { this.pendingApplicantCount = pendingApplicantCount; }

	public Integer getInvitedApplicantCount() {
		return invitedApplicantCount;
	}

	public void setInvitedApplicantCount(Integer invitedApplicantCount) { this.invitedApplicantCount = invitedApplicantCount; }

	public Calendar getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Calendar createdOn) {
		this.createdOn = createdOn;
	}

	public Long getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public String getOwnerFullName() {
		return creatorFullName;
	}

	public void setOwnerFullName(String ownerFullName) {
		this.creatorFullName = ownerFullName;
	}

	public String getOwnerUserNumber() {
		return ownerUserNumber;
	}

	public void setOwnerUserNumber(String ownerUserNumber) {
		this.ownerUserNumber = ownerUserNumber;
	}

	public String getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	public void setMember(boolean member) {
		this.member = member;
	}

	public boolean isMember() {
		return member;
	}

	public void setOwner(boolean owner) {
		this.owner = owner;
	}

	public boolean isOwner() {
		return owner;
	}

	public boolean isShared() { return isShared; }

	public void setIsShared(boolean isShared) { this.isShared = isShared; }

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public Long getGroupId() {
		return groupId;
	}

	public boolean isSharedByMe(Long myCompanyId) {
		return myCompanyId != null && myCompanyId.equals(companyId) && isShared;
	}

	public boolean isSharedWithMe(Long myCompanyId) {
		return myCompanyId != null && !myCompanyId.equals(companyId) && isShared;
	}

	public Long getIndustry() {
		return industry;
	}

	public void setIndustry(Long industry) {
		this.industry = industry;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(final String uuid) {
		this.uuid = uuid;
	}
}
