export const UPDATE_DELIVERABLES_INSTRUCTIONS = 'UPDATE_DELIVERABLES_INSTRUCTIONS';
export const UPDATE_DELIVERABLES_TIME = 'UPDATE_DELIVERABLES_TIME';
export const ADD_DELIVERABLE = 'ADD_DELIVERABLE';
export const REMOVE_DELIVERABLE = 'REMOVE_DELIVERABLE';
