export const UPDATE_FIRST_TO_ACCEPT_GROUP_IDS = 'UPDATE_FIRST_TO_ACCEPT_GROUP_IDS';
export const UPDATE_FIRST_TO_ACCEPT_RESOURCE_NUMBERS = 'UPDATE_FIRST_TO_ACCEPT_RESOURCE_NUMBERS';
export const UPDATE_FIRST_TO_ACCEPT_VENDOR_NUMBERS = 'UPDATE_FIRST_TO_ACCEPT_VENDOR_NUMBERS';
export const CLEAR_INVITEES = 'CLEAR_INVITEES';
