export const UPDATE_NEED_TO_APPLY_GROUP_IDS = 'UPDATE_NEED_TO_APPLY_GROUP_IDS';
export const UPDATE_NEED_TO_APPLY_RESOURCE_NUMBERS = 'UPDATE_NEED_TO_APPLY_RESOURCE_NUMBERS';
export const UPDATE_NEED_TO_APPLY_VENDOR_NUMBERS = 'UPDATE_NEED_TO_APPLY_VENDOR_NUMBERS';
export const CLEAR_INVITEES = 'CLEAR_INVITEES';
